(function(){
  'use strict';
  var reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var coarse=window.matchMedia('(pointer: coarse)').matches;
  var config=window.UberritoNewHome||{};
  function clamp(v,min,max){return Math.min(Math.max(v,min),max)}

  function loader(){var el=document.querySelector('.nv-loader');if(!el)return;var bar=el.querySelector('.nv-loader__bar'),fill=el.querySelector('.nv-loader__bar span'),p=0,t;document.documentElement.classList.add('nv-loading');function finish(){clearInterval(t);p=100;if(fill)fill.style.width='100%';if(bar)bar.setAttribute('aria-valuenow','100');setTimeout(function(){el.classList.add('is-done');document.documentElement.classList.remove('nv-loading')},reduced?30:220)}if(reduced){finish();return}t=setInterval(function(){p=Math.min(p+Math.floor(Math.random()*12+8),92);if(fill)fill.style.width=p+'%';if(bar)bar.setAttribute('aria-valuenow',String(p))},115);if(document.readyState==='complete')setTimeout(finish,750);else{window.addEventListener('load',function(){setTimeout(finish,500)},{once:true});setTimeout(finish,2200)}}

  function offers(){var rail=document.querySelector('.nv-offers');if(!rail)return;var data=[
    {label:'New member offer',text:'New here? Get <strong>FREE</strong> small chips & queso.',cta:'Join now',image:'rewards-chips.webp',href:config.rewardsUrl},
    {label:'Member exclusive',text:'Get texts + emails. Enjoy a <strong>FREE drink</strong> today.',cta:'Get the offer',image:'bowl-and-glass.webp',href:config.rewardsUrl},
    {label:'NÜ Rewards',text:'Eat. Earn. Eat free. <strong>Rewards start here.</strong>',cta:'Sign up',image:'rewards-burritos.webp',href:config.rewardsUrl},
    {label:'Order direct',text:'Get <strong>$5 off</strong> when you order on Uberrito.com.',cta:'Order now',image:'rewards-nachos.webp',href:config.orderUrl}
  ],img=rail.querySelector('.nv-offers__image'),label=rail.querySelector('small'),copy=rail.querySelector('.nv-offers__copy p'),link=rail.querySelector('.nv-offers__link'),count=rail.querySelector('[data-offer-current]'),pause=rail.querySelector('[data-offer-pause]'),index=0,paused=false,timer;
    function show(n){index=(n+data.length)%data.length;var o=data[index];if(img){img.style.opacity='0';img.style.transform='translateY(7px) scale(.92)'}setTimeout(function(){if(img){img.src=(config.assetsUrl||'')+o.image;img.style.opacity='1';img.style.transform=''}if(label)label.textContent=o.label;if(copy)copy.innerHTML=o.text;if(link){link.href=o.href||'#';link.innerHTML=o.cta+' <span aria-hidden="true">→</span>'}if(count)count.textContent=String(index+1)},170)}
    function restart(){clearInterval(timer);if(!paused)timer=setInterval(function(){show(index+1)},5200)}
    var prev=rail.querySelector('[data-offer-prev]'),next=rail.querySelector('[data-offer-next]');if(prev)prev.onclick=function(){show(index-1);restart()};if(next)next.onclick=function(){show(index+1);restart()};if(pause)pause.onclick=function(){paused=!paused;pause.textContent=paused?'▶':'Ⅱ';pause.setAttribute('aria-label',paused?'Resume offer rotation':'Pause offer rotation');restart()};restart()}

  function heroSlider(){var hero=document.querySelector('.nv-hero'),slides=hero&&hero.querySelectorAll('[data-hero-slide]'),dots=hero&&hero.querySelectorAll('[data-hero-dot]');if(!hero||!slides||slides.length<2)return;var index=0,timer,paused=false;function show(n){index=(n+slides.length)%slides.length;slides.forEach(function(s,i){var active=i===index;s.classList.toggle('is-active',active);s.setAttribute('aria-hidden',active?'false':'true')});dots.forEach(function(d,i){d.classList.toggle('is-active',i===index)})}function start(){clearInterval(timer);if(!paused&&!reduced)timer=setInterval(function(){show(index+1)},7000)}var prev=hero.querySelector('[data-hero-prev]'),next=hero.querySelector('[data-hero-next]');if(prev)prev.onclick=function(){show(index-1);start()};if(next)next.onclick=function(){show(index+1);start()};dots.forEach(function(d){d.onclick=function(){show(Number(d.dataset.heroDot));start()}});hero.addEventListener('mouseenter',function(){paused=true;clearInterval(timer)});hero.addEventListener('mouseleave',function(){paused=false;start()});show(0);start()}

  function navigation(){var head=document.querySelector('.nv-site-head'),toggle=document.querySelector('.nv-menu-toggle'),menu=document.querySelector('.nv-mobile-menu'),busy=false;if(!head)return;function update(){head.classList.toggle('is-scrolled',scrollY>90);busy=false}addEventListener('scroll',function(){if(busy)return;busy=true;requestAnimationFrame(update)},{passive:true});update();if(toggle&&menu){toggle.onclick=function(){var open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));menu.hidden=open};menu.onclick=function(e){if(!e.target.closest('a'))return;toggle.setAttribute('aria-expanded','false');menu.hidden=true}}}

  function reveals(){var items=document.querySelectorAll('[data-nv-reveal]');if(!items.length||reduced||!('IntersectionObserver'in window)){items.forEach(function(i){i.classList.add('is-visible')});return}var ob=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('is-visible');ob.unobserve(e.target)}})},{threshold:.1,rootMargin:'0px 0px -7%'});items.forEach(function(i){ob.observe(i)})}
  function parallax(){if(reduced||coarse)return;document.querySelectorAll('.nv-parallax').forEach(function(el){var depth=Number(el.dataset.depth||12);el.onpointermove=function(e){var r=el.getBoundingClientRect(),x=((e.clientX-r.left)/r.width-.5)*depth,y=((e.clientY-r.top)/r.height-.5)*depth;el.style.transform='translate3d('+x+'px,'+y+'px,0)'};el.onpointerleave=function(){el.style.transform=''}})}
  function magnetic(){if(reduced||coarse)return;document.querySelectorAll('.nv-magnetic').forEach(function(el){el.onpointermove=function(e){var r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.13,y=(e.clientY-r.top-r.height/2)*.15;el.style.transform='translate3d('+x+'px,'+y+'px,0)'};el.onpointerleave=function(){el.style.transform=''}})}

  function pointerCharacters(){if(reduced||coarse)return;var faces=document.querySelectorAll('.nv-face-button,.nv-burrito-pal');if(!faces.length)return;window.addEventListener('pointermove',function(e){faces.forEach(function(face){var r=face.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,len=Math.max(Math.hypot(dx,dy),1),x=clamp(dx/len*5,-5,5),y=clamp(dy/len*5,-5,5);face.style.setProperty('--eye-x',x+'px');face.style.setProperty('--eye-y',y+'px');if(face.classList.contains('nv-burrito-pal')){face.style.setProperty('--arm-left',clamp(-25+dy/24,-55,20)+'deg');face.style.setProperty('--arm-right',clamp(25-dy/24,-20,55)+'deg');face.style.transform='translateX(-50%) rotate('+clamp(dx/90,-7,7)+'deg)'}})},{passive:true})}

  function flight(){var section=document.querySelector('.nv-flight'),svg=document.querySelector('.nv-flight__path'),path=document.querySelector('#nv-flight-path'),plane=document.querySelector('.nv-plane');if(!section||!svg||!path||!plane||reduced||innerWidth<768)return;var total=path.getTotalLength(),busy=false;function update(){var max=Math.max(section.offsetHeight-innerHeight,1),p=clamp((scrollY-section.offsetTop)/max,0,1),point=path.getPointAtLength(total*p),ahead=path.getPointAtLength(Math.min(total,total*p+2)),r=svg.getBoundingClientRect(),x=r.left+point.x/1400*r.width,y=r.top+point.y/620*r.height,a=Math.atan2(ahead.y-point.y,ahead.x-point.x)*180/Math.PI;plane.style.transform='translate3d('+x+'px,'+y+'px,0) translate(-50%,-50%) rotate('+a+'deg)';busy=false}addEventListener('scroll',function(){if(busy)return;busy=true;requestAnimationFrame(update)},{passive:true});addEventListener('resize',update,{passive:true});update()}

  function previews(){if(coarse)return;var section=document.querySelector('.nv-bottom-nav'),preview=document.querySelector('.nv-bottom-preview'),img=preview&&preview.querySelector('img');if(!section||!preview||!img)return;section.querySelectorAll('[data-preview]').forEach(function(link){link.onpointerenter=function(){img.src=(config.assetsUrl||'')+link.dataset.preview;preview.classList.add('is-visible')};link.onpointerleave=function(){preview.classList.remove('is-visible')}});section.onpointermove=function(e){preview.style.left=e.clientX+'px';preview.style.top=e.clientY+'px'}}

  function fruitNinja(){var footer=document.querySelector('.nv-footer'),stage=footer&&footer.querySelector('.nv-ninja-stage'),items=stage&&stage.querySelectorAll('[data-ninja-item]'),trail=stage&&stage.querySelector('.nv-slash-trail');if(!footer||!stage||!items.length||reduced)return;var animations=[],last={x:0,y:0,t:0},trailTimer;
    function start(){if(animations.length)return;var width=footer.clientWidth,height=footer.clientHeight;items.forEach(function(item,i){var startX=(.08+i*.2)*width,endX=startX+(i%2?-.12:.12)*width,duration=2500+i*190;animations.push(item.animate([{opacity:0,transform:'translate3d('+startX+'px,'+(height+120)+'px,0) rotate(0deg)'},{opacity:1,offset:.1},{opacity:1,transform:'translate3d('+endX+'px,'+(-170-i*25)+'px,0) rotate('+(i%2?-310:340)+'deg)',offset:.82},{opacity:0,transform:'translate3d('+(endX+(i%2?-40:40))+'px,'+(height+80)+'px,0) rotate('+(i%2?-520:560)+'deg)'}],{duration:duration,delay:i*260,iterations:Infinity,easing:'cubic-bezier(.45,.05,.55,.95)'}))})}
    function stop(){animations.forEach(function(a){a.cancel()});animations=[]}
    function slash(e){var r=stage.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,now=performance.now(),dx=x-last.x,dy=y-last.y,speed=Math.hypot(dx,dy)/Math.max(now-last.t,1);if(trail&&speed>.25){trail.style.left=x+'px';trail.style.top=y+'px';trail.style.setProperty('--slash-angle',Math.atan2(dy,dx)*180/Math.PI+'deg');trail.classList.add('is-live');clearTimeout(trailTimer);trailTimer=setTimeout(function(){trail.classList.remove('is-live')},90)}if(speed>.35)items.forEach(function(item){var b=item.getBoundingClientRect();if(e.clientX>b.left-18&&e.clientX<b.right+18&&e.clientY>b.top-18&&e.clientY<b.bottom+18){item.classList.add('is-sliced');setTimeout(function(){item.classList.remove('is-sliced')},650)}});last={x:x,y:y,t:now}}
    stage.addEventListener('pointermove',slash,{passive:true});if('IntersectionObserver'in window){new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting)start();else stop()})},{threshold:.14}).observe(footer)}else start()}

  function init(){loader();offers();heroSlider();navigation();reveals();parallax();magnetic();pointerCharacters();flight();previews();fruitNinja()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
